import SwiftUI
import CoreLocation
import UIKit

/// Journey Summary Report: per-trip asset, driver and type, reverse-geocoded start and
/// end locations, with CSV export and Print / PDF.
struct JourneyReportView: View {
    let trips: [Trip]
    @Environment(TrackerStore.self) private var store
    @Environment(\.dismiss) private var dismiss

    @State private var rows: [JourneyRow] = []
    @State private var defaultAsset = ""
    @State private var defaultDriver = ""
    @State private var defaultType: TripType = .business

    var body: some View {
        NavigationStack {
            Form {
                Section("Report") {
                    TextField("Asset Name", text: $defaultAsset)
                    TextField("Default Driver", text: $defaultDriver)
                    Picker("Default Type", selection: $defaultType) {
                        ForEach(TripType.allCases) { Text($0.rawValue).tag($0) }
                    }
                    if let first = trips.first, let last = trips.last {
                        LabeledContent("Period", value: "\(MelbourneTime.fullDate(first.summary.start)) – \(MelbourneTime.fullDate(last.summary.end))")
                    }
                    LabeledContent("Device", value: "IMEI \(store.deviceID) · FW \(store.firmware)")
                }
                Section {
                    ForEach($rows) { $row in
                        JourneyRowView(row: $row, defaultAsset: defaultAsset, defaultDriver: defaultDriver, defaultType: defaultType)
                    }
                } footer: {
                    Text(JourneyReport.summaryLine(trips))
                }
            }
            .navigationTitle("Journey Summary Report")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) { Button("Done") { dismiss() } }
                ToolbarItemGroup(placement: .primaryAction) {
                    ShareLink(item: csvFile(), preview: SharePreview("Journey Report CSV")) {
                        Label("Export CSV", systemImage: "tablecells")
                    }
                    Button { printReport() } label: { Label("Print / PDF", systemImage: "printer") }
                }
            }
            .task { await prepareRows() }
        }
    }

    private func prepareRows() async {
        guard rows.isEmpty else { return }
        rows = trips.map { JourneyRow(trip: $0) }
        // Geocode sequentially; CLGeocoder throttles bursts of requests.
        for i in rows.indices {
            let pts = rows[i].trip.pings
            if let s = pts.first { rows[i].startLocation = await ReverseGeocoder.shared.address(for: s) }
            if let e = pts.last { rows[i].endLocation = await ReverseGeocoder.shared.address(for: e) }
        }
    }

    private var csv: String {
        JourneyReport.csv(rows: rows, defaultAsset: defaultAsset, defaultDriver: defaultDriver, defaultType: defaultType)
    }

    private func csvFile() -> URL {
        let stamp = MelbourneTime.dateKey(.now)
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("WHG_Journey_Report_\(stamp).csv")
        try? csv.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private func printReport() {
        let esc: (String) -> String = {
            $0.replacingOccurrences(of: "&", with: "&amp;").replacingOccurrences(of: "<", with: "&lt;")
        }
        let parsed = CSVParser.rows(csv)
        let header = parsed.first.map { "<tr>" + $0.map { "<th>\(esc($0))</th>" }.joined() + "</tr>" } ?? ""
        let body = parsed.dropFirst().map { "<tr>" + $0.map { "<td>\(esc($0))</td>" }.joined() + "</tr>" }.joined()
        let html = """
        <html><head><style>
        body{font-family:-apple-system;font-size:9px} table{border-collapse:collapse;width:100%}
        th,td{border:1px solid #ccc;padding:3px;text-align:left} th{background:#eee}
        </style></head><body>
        <h2>Journey Summary Report</h2>
        <p>IMEI \(esc(store.deviceID)) · FW \(esc(store.firmware))</p>
        <table>\(header)\(body)</table>
        <p>\(esc(JourneyReport.summaryLine(trips)))</p>
        <p style="color:#888">Generated by WHG Telematics</p>
        </body></html>
        """
        let info = UIPrintInfo(dictionary: nil)
        info.outputType = .general
        info.jobName = "Journey Summary Report"
        info.orientation = .landscape
        let controller = UIPrintInteractionController.shared
        controller.printInfo = info
        controller.printFormatter = UIMarkupTextPrintFormatter(markupText: html)
        _ = controller.present(animated: true)
    }
}

struct JourneyRowView: View {
    @Binding var row: JourneyRow
    let defaultAsset: String
    let defaultDriver: String
    let defaultType: TripType

    var body: some View {
        let s = row.trip.summary
        DisclosureGroup {
            TextField("Asset name", text: Binding(get: { row.asset ?? defaultAsset }, set: { row.asset = $0 }))
            TextField("Driver name", text: Binding(get: { row.driver ?? defaultDriver }, set: { row.driver = $0 }))
            Picker("Type", selection: Binding(get: { row.type ?? defaultType }, set: { row.type = $0 })) {
                ForEach(TripType.allCases) { Text($0.rawValue).tag($0) }
            }
        } label: {
            VStack(alignment: .leading, spacing: 4) {
                HStack {
                    Text("T\(row.trip.id)").font(.caption.weight(.bold)).foregroundStyle(Theme.accent)
                    Text("\(MelbourneTime.shortDate(s.start)) \(MelbourneTime.time(s.start)) → \(MelbourneTime.time(s.end))")
                        .font(.caption.monospacedDigit())
                    Spacer()
                    Text(s.closedByDP4 ? "DP4 ✓" : "Timeout")
                        .font(.caption2.weight(.semibold))
                        .foregroundStyle(s.closedByDP4 ? Theme.green : Theme.yellow)
                }
                HStack(spacing: 12) {
                    Text(String(format: "%.2f km", s.distanceKm)).foregroundStyle(Theme.green)
                    Text(MelbourneTime.duration(minutes: s.durationMin))
                    Text(String(format: "%.0f km/h", s.maxSpeed)).foregroundStyle(Theme.red)
                    Text((row.type ?? defaultType).rawValue).foregroundStyle(Theme.muted)
                }
                .font(.caption)
                Text("From: \(row.startLocation ?? "Locating…")").font(.caption2).foregroundStyle(Theme.muted)
                Text("To: \(row.endLocation ?? "Locating…")").font(.caption2).foregroundStyle(Theme.muted)
            }
        }
    }
}

/// Reverse geocoding with Apple's geocoder and an in-memory cache keyed to ~1 m.
actor ReverseGeocoder {
    static let shared = ReverseGeocoder()
    private var cache: [String: String] = [:]
    private let geocoder = CLGeocoder()

    func address(for ping: Ping) async -> String {
        let key = String(format: "%.5f,%.5f", ping.latitude, ping.longitude)
        if let hit = cache[key] { return hit }
        var result = key.replacingOccurrences(of: ",", with: ", ")
        if let mark = try? await geocoder.reverseGeocodeLocation(CLLocation(latitude: ping.latitude, longitude: ping.longitude)).first {
            let parts = [mark.thoroughfare, mark.subLocality, mark.locality, mark.administrativeArea]
                .compactMap { $0 }.filter { !$0.isEmpty }
            if !parts.isEmpty { result = parts.joined(separator: ", ") }
        }
        cache[key] = result
        return result
    }
}
